[env:seeed_xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino

lib_ldf_mode = deep+
lib_archive = no
build_flags = -DUSE_TINYUSB

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    sparkfun/SparkFun LSM9DS1 IMU@^2.0.0
